Repository RainbowMarkets/RainbowMarket, pull requests merged in 2022-12, with the labels that each got.

#8 Feat/splash기능구현
  src/components/Login/LoginModal/LoginModal.jsx
  src/components/Splash/Splash.jsx
  src/pages/Splash/SplashPage.jsx
Labels: help wanted

#21 Feat/top bar 컴포넌트 마크업 스타일링
  src/App.js
  src/components/TopBar/CommonTopBar/CommonTopBar.jsx
  src/components/TopBar/FollowTopBar/FollowTopBar.jsx
  src/components/TopBar/FollowTopBar/styledFollowTopBar.jsx
  src/components/TopBar/MainTopBar/MainTopBar.jsx
  src/components/TopBar/MainTopBar/styledMainTopBar.jsx
  src/components/TopBar/SaveTopBar/SaveTopBar.jsx
  src/components/TopBar/SearchTopBar/SearchTopBar.jsx
  src/components/TopBar/SearchTopBar/styledSearchTopBar.jsx
  src/components/TopBar/UpLoadTopBar/UpLoadTopBar.jsx
  src/components/TopBar/commonStyledTopBar.jsx
Labels: 마크업, 스타일

#27 :art: style : splash와 로그인모달창 스타일추가
  src/assets/images/google.png
  src/components/Login/LoginModal/loginModal.style.js
  src/components/Splash/Splash.style.js
Labels: enhancement

#32 :construction_worker: feat: 유저목록, 서치페이지 마크업 및 스타일링
  src/App.js
  src/components/common/UserList/UserList.jsx
  src/components/common/UserList/styledUserList.jsx
  src/pages/Search/Search.jsx
  src/pages/Search/styledSearch.jsx
Labels: 마크업, 스타일

#37 :art: style: 내브바, 탑바, 404페이지 스타일 리팩토링
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/styledNavBar.jsx
  src/components/TopBar/CommonTopBar/CommonTopBar.jsx
  src/components/TopBar/FollowTopBar/FollowTopBar.jsx
  src/components/TopBar/FollowTopBar/styledFollowTopBar.jsx
  src/components/TopBar/MainTopBar/MainTopBar.jsx
  src/components/TopBar/SearchTopBar/SearchTopBar.jsx
  src/components/TopBar/commonStyledTopBar.jsx
  src/pages/NotFound/styledNotFound.jsx
Labels: 스타일

#41 Feat/메인피드마크업
  src/App.js
  src/components/Navbar/styledNavBar.jsx
  src/components/TopBar/commonStyledTopBar.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/IsHaveFeed/IsHaveFeed.jsx
  src/pages/Home/NoFeed/NoFeed.jsx
  src/pages/Home/NoFeed/styledNoFeed.jsx
Labels: 마크업, 스타일

#43 :construnction_worker:feat: 회원가입마크업
  src/components/Join/JoinWithEmail/JoinWithEmail.jsx
Labels: 마크업

#48 Feat/top bar리팩토링
  src/App.js
  src/components/Navbar/styledNavBar.jsx
  src/components/TopBar/BackButton.jsx
  src/components/TopBar/CommonTopBar/CommonTopBar.jsx
  src/components/TopBar/FollowTopBar/FollowTopBar.jsx
  src/components/TopBar/SaveTopBar/SaveTopBar.jsx
  src/components/TopBar/SearchTopBar/SearchTopBar.jsx
  src/components/TopBar/UpLoadTopBar/UpLoadTopBar.jsx
  src/components/TopBar/commonStyledTopBar.jsx
  src/pages/Home/Home.jsx
  src/pages/NotFound/NotFound.jsx
  src/pages/NotFound/styledNotFound.jsx
  src/pages/Post/Post.jsx
  src/pages/Search/Search.jsx
Labels: 기능구현

#51 :construction_worker: feat: 내브바 활성화기능 구현 및 헤더 추가
  src/App.js
  src/GlobalStyle.js
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/styledNavBar.jsx
  src/components/TopBar/commonStyledTopBar.jsx
  src/pages/Chat/Chat.jsx
  src/pages/Profile/Profile.jsx
Labels: 기능구현

#53 :construction_worker: feat: 회원가입기능추가
  src/components/Join/JoinWithEmail/JoinWithEmail.jsx
Labels: 마크업, 기능구현

#55 :adhesive_bandage: fix: JoinWithEmail.jsx파일충돌난부분수정
  src/components/Join/JoinWithEmail/JoinWithEmail.jsx
Labels: enhancement

#56 :adhesive_bandage: fix: 회원가입파일수정
  src/components/Join/JoinWithEmail/JoinWithEmail.jsx
  src/components/Join/JoinWithEmail/JoinWithEmail.style.js
Labels: enhancement

#63 Feat/메인피드 게시글 불러오기
  src/App.js
  src/components/Navbar/Navbar.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/IsHaveFeed/IsHaveFeed.jsx
  src/pages/Home/IsHaveFeed/styledisHaveFeed.jsx
  src/pages/Home/NoFeed/styledNoFeed.jsx
Labels: 기능구현

#65 :art: style: 회원가입스타일링
  src/components/Join/JoinWithEmail/JoinWithEmail.style.jsx
  src/components/Login/LoginModal/loginModal.style.jsx
Labels: 스타일

#66 :adhesive_bandage: fix: 회원가입스타일링수정
  src/App.js
  src/components/Join/JoinWithEmail/JoinWithEmail.jsx
  src/components/Join/JoinWithEmail/JoinWithEmail.style.js
Labels: enhancement

#74 Feat/top bar리팩토링
  src/components/Navbar/Navbar.jsx
  src/components/Posts/PostDetail.jsx
  src/components/TopBar/CommonTopBar/CommonTopBar.jsx
  src/components/TopBar/commonStyledTopBar.jsx
  src/components/common/Modal/Alert/DeleteAlert.jsx
  src/components/common/Modal/Alert/LogOutAlert.jsx
  src/components/common/Modal/Alert/styledDeleteAlert.jsx
  src/components/common/Modal/Modal/Modal.jsx
  src/components/common/Modal/Modal/styledModal.jsx
  src/pages/Chat/Chat.jsx
  src/pages/Home/IsHaveFeed/IsHaveFeed.jsx
  src/pages/NotFound/styledNotFound.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileEdit/ProfileEdit.jsx
Labels: 기능구현

#75 :adhesive_bandage: fix: profile페이지 모달 동작 오류 수정
  src/components/Posts/PostDetail.jsx
  src/components/common/Modal/Modal/Modal.jsx
Labels: bug

#77 :adhesive_bandage: fix: 회원가입화면수정 및 유효성검사수정
  src/GlobalStyle.js
  src/components/Join/JoinWithEmail/JoinWithEmail.jsx
  src/components/Join/JoinWithEmail/JoinWithEmail.style.jsx
  src/pages/Join/JoinWithEmailPage.jsx
Labels: documentation

#87 Feat/게시글삭제
  src/components/Posts/Comment/CommentDetail/CommentDetail.jsx
  src/components/Posts/PostDetail.jsx
  src/components/common/Modal/Alert/DeleteAlert.jsx
  src/components/common/Modal/Modal/PostModal.jsx
  src/components/common/PostFormat/PostContent/PostContent.jsx
  src/pages/Home/IsHaveFeed/IsHaveFeed.jsx
  src/pages/Post/Post.jsx
Labels: 기능구현

#93 Feat/댓글삭제
  src/components/Posts/Comment/CommentAdd/CommentAdd.jsx
  src/components/Posts/Comment/CommentAdd/styledCommentAdd.jsx
  src/components/Posts/Comment/CommentDetail/CommentDetail.jsx
  src/components/Posts/PostBtn/PostCommentBtn/PostCommentBtn.jsx
  src/components/Posts/PostDetail.jsx
  src/components/common/Modal/Alert/CommentAlert.jsx
  src/components/common/Modal/Modal/CommentModal.jsx
  src/components/common/PostFormat/PostContent/PostContent.jsx
Labels: 기능구현

#95 Feat/서치기능
  src/components/Navbar/Navbar.jsx
  src/components/TopBar/SearchTopBar/SearchTopBar.jsx
  src/components/common/Modal/Modal/Modal.jsx
  src/components/common/Modal/Modal/PostModal.jsx
  src/components/common/Modal/Modal/styledModal.jsx
  src/components/common/UserList/UserList.jsx
  src/components/common/UserList/styledUserList.jsx
  src/pages/Search/Search.jsx
  src/pages/Search/styledSearch.jsx
Labels: 기능구현

#97 :adhesive_bandage: fix : 충돌해결
  src/App.js
Labels: enhancement

#103 Feat/서치기능
  src/components/TopBar/SearchTopBar/SearchTopBar.jsx
  src/components/common/UserList/UserList.jsx
  src/components/common/UserList/styledUserList.jsx
  src/pages/Search/Search.jsx
Labels: 기능구현

#108 :construction_worker: feat:로그인기능구현
  src/App.js
  src/components/Join/JoinWithEmail/JoinWithEmail.jsx
  src/components/common/Login/Login.jsx
  src/components/common/Login/Login.style.jsx
Labels: 마크업, 스타일, 기능구현

#116 Feat/서치기능
  src/components/TopBar/SearchTopBar/SearchTopBar.jsx
  src/components/common/UserList/UserList.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/IsHaveFeed/IsHaveFeed.jsx
  src/pages/Search/Search.jsx
Labels: bug, 기능구현

#122 :construction_worker: feat: 게시글, 프로필 수정 후 뒤로가기 방지기능 구현
  src/App.js
  src/pages/Post/PostEdit.jsx
  src/pages/Profile/ProfileEdit.jsx
Labels: 기능구현

#126 Feat/화면이동
  src/App.js
  src/components/Join/JoinWithEmail/JoinWithEmail.jsx
  src/components/common/SetProfile/SetProfile.jsx
  src/components/common/SetProfile/SetProfileImage/SetProfileImage.jsx
  src/hooks/useLogin.jsx
  src/hooks/useUserContext.jsx
Labels: enhancement
